### ISSUE TITLE
Pourquoi ne pas utiliser endl ?

### ISSUE THREAD

**Issue by mhammerc** [P1kachu/ProgrammingLearning#2]
Bonjour !
Dans la fiche sur le C++ tu préfère utiliser \n au lieu de std::endl. Pourquoi pas utiliser std::endl ?
Notamment ici :

https://github.com/P1kachu/ProgrammingLearning/blob/master/Corrections/Correction_C++.cpp#L185-L189

**Comment by P1kachu** [comment]
Hey !
C'etait juste pour la clarté. J'ai utilisé en alternance `endl` et `\n` pour montrer que les deux fonctionnaient, et que dans cet exemple principalement les `<< endl` auraient étés lourds.

**Comment by mhammerc** [comment]
Dac :p
